server{
	listen 80;
	server_name asbait.cloud;

	location /downloads{
	
		#actual file path
		alias /var/file/;

		#Enables directory listing
		#Shows all files and folders inside /var/files/
		autoindex on;

	}
}
