upstream backend {
	ip_hash; #load balance alogithm 1)least_conn 2)round_robin(default) 3)weightd round_robin 4)least_time 
	#least_time header;
	#least_conn;
	server <private_ip>;
	server <private_ip>;

	#if weighted rr

	#server <ip> weight=3;
	#server <ip> weight=1;
}

server{
	listen 80;
	server_name asbait.cloud;

	location /{
	
		proxy_pass http://backend; # here mention the upstream_name
		proxy_set_header HOST $host; # sends the hostname to backend_app
		proxy_set_header X-Real-IP $remote_addr; #send user_ip to backend_app
		proxy_set_header X-Froward-For $proxy_add_x_forward_for;

	
	}
}
