
#cache_store_path
proxy_cache_path /var/cache/nginx/ max_size=2g levels=1:2 key_zones=mychache:10m inactive=60m use_temp_path=off;

server{
	listen 80;
	server_name asbaitdev.cloud;

	location /{
		proxy_pass http://localhost:3000
		
		#cache_enable
		proxy_cache mycache;
		

		# Cache rules
		proxy_cache_valid 200 10m;
		proxy_cache_valid 404 10m;
		

		# Add headers to check cache status
		add_header X-Cache-Status $upstream_cache_status;
	}
}
